spring:
  redis:
    cluster:
      nodes: "192.168.1.11:7000,192.168.1.11:7001,192.168.1.11:7002"
    password:
    lettuce:
      pool:
        max-active: 1500
        max-wait: 5000
        max-idle: 500
        min-idle: 100
    timeout: 60000

#  单机模式
#  redis:
#    database: 0
#    host: localhost
#    port: 6379
#    password:
